---
- name: Check that CA secret is present
  shell: kubectl get secret -n {{ namespace }} {{ NUXEO_BACKINGS_NAME }}-ca -o custom-columns=name:.metadata.name --no-headers
  register: casecret
  changed_when: False
  check_mode: no
  ignore_errors: yes
- name: Fail if CA secret is not present
  fail:
    msg: A global CA key has to be defined for {{ NUXEO_BACKINGS_NAME }}
  when: casecret.rc != 0

- name: Set secured setup
  set_fact: 
    secured: true