---

- name: "Kafka service binding state={{ state }}"
  block:
    - name: "Create Kafka service binding from template"
      template:
        src: service_binding.yml.j2
        dest: /tmp/kafka_service_binding.yml
      vars:
        service_binding_name: "{{ kafka_servicebinding_name }}"
        service_to_bind: "{{ kafkaServiceName }}"
        secret_name: "{{ kafka_credentials_name }}"

    - name: "Create Kafka binding"
      shell: kubectl create --filename=/tmp/kafka_service_binding.yml
  when:
    - state == "present"

- name: "Nuxeo Kafka binding state={{ state }}"
  shell: kubectl delete --ignore-not-found=true servicebinding {{ kafka_servicebinding_name }} -n {{ namespace }}
  when:
    - state == "absent"

