---

- name: "Verify {{ name }} objects exist"
  set_fact:
    admin_secret: "{{ admin_secret_lookup }}"
    connect_secret: "{{ connect_secret_lookup }}"
    init_config: "{{ init_configmap_lookup }}"
    nuxeo_route: "{{ nuxeo_route_lookup }}"
  retries: 10
  delay: 5
  until:
    - admin_secret_lookup
    - connect_secret_lookup
    - init_configmap_lookup
    - nuxeo_service_lookup
    - nuxeo_route_lookup
    
