---

- name: "Verify {{ name }} objects exist"
  set_fact:
    admin_secret: "{{ admin_secret_lookup }}"
    connect_secret: "{{ connect_secret_lookup }}"
    init_config: "{{ init_configmap_lookup }}"
    nuxeo_route: "{{ route_lookup }}"
    binaries_pvc: "{{ binaries_pvc_lookup }}"
    transientstore_pvc: "{{ transientstore_pvc_lookup }}"
    data_pvc: "{{ data_pvc_lookup }}"
    log_pvc: "{{ log_pvc_lookup }}"
  retries: 10
  delay: 5
  until:
    - admin_secret_lookup
    - connect_secret_lookup
    - init_configmap_lookup
    - service_lookup
    - cluster == "kubernetes" or route_lookup
    - binaries_pvc_lookup or not binaries_usePVC
    - transientstore_pvc_lookup or not transientstore_usePVC
    - data_pvc_lookup or not data_usePVC
    - log_pvc_lookup or not log_usePVC
    - log_pvc_lookup or not log_usePVC

    
