---

- name: "Verify {{ name }} objects removed"
  set_fact:
    ca_secret: "{{ ca_secret_lookup }}"
    config: "{{ configmap_lookup }}"
    sg_config: "{{ sg_configmap_lookup }}"
    service_client: "{{ service_client_lookup }}"
    service_master: "{{ service_master_lookup }}"
    service_account: "{{ elasticsearch_serviceaccount_lookup }}"
    statefulset_data: "{{ statefulset_data_lookup }}"
    statefulset_client: "{{ statefulset_client_lookup }}"
    statefulset_master: "{{ statefulset_master_lookup }}"
  retries: 10
  delay: 5
  until:
    - not ( use_searchguard and ca_secret_lookup )
    - not configmap_lookup
    - not ( sg_configmap_lookup and use_searchguard )
    - not service_client_lookup
    - not service_master_lookup
    - not elasticsearch_serviceaccount_lookup
    - not statefulset_data_lookup
    - not statefulset_client_lookup
    - not statefulset_master_lookup
