- name: nuxeo-elasticsearch-apb playbook to deprovision the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    state: absent
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: nuxeo-elasticsearch-apb
    playbook_debug: false