- name: nuxeo-elasticsearch-apb playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansibleplaybookbundle.asb-modules
  - role: nuxeo-elasticsearch-apb
    playbook_debug: false
  vars:
    apb_action: provision