- name: Playbook to provision an ARender service
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: nuxeo-arender-apb
  vars:
    apb_action: provision