
- name: "Update last operation"
  asb_last_operation:
    description: "0%: Starting"
  when: in_cluster


- name: "ca secret state={{ state }}"
  include_tasks: "create_ca_secret.yml"
  when: state == "present" and tls_enabled

- name: "ca secret state={{ state }}"
  shell: kubectl delete --ignore-not-found=true secret {{ ca_secret_name }} -n {{ namespace }}
  when: state == "absent" and tls_enabled


- include_tasks: zookeeper.yml
- include_tasks: kafka.yml


- name: "Update last operation"
  asb_last_operation:
    description: "50%: Cluster objects state={{ state }}"
  when: in_cluster

- include_tasks: "verify_{{ apb_action }}.yml"

- name: encode bind credentials
  asb_encode_binding:
    fields:
      uri: "{{ service_uri }}"
      tls_cacert: "{{ tls_cacert_lookup | b64encode }}"
  when: state == "present"


- name: "Update last operation"
  asb_last_operation:
    description: "100%: Done"
  when: in_cluster
