
- name: "Update last operation"
  asb_last_operation:
    description: "0%: Starting"
  when: in_cluster

- name: "ca secret state={{ state }}"
  include_tasks: "create_ca_secret.yml"
  when: state == "present" and tls_enabled

- name: "ca secret state={{ state }}"
  shell: kubectl delete --ignore-not-found=true secret {{ ca_secret_name }} -n {{ namespace }}
  when: state == "absent" and tls_enabled

- include_tasks: zookeeper.yml

- name: "Update last operation"
  asb_last_operation:
    description: "25%: Cluster objects state={{ state }}"
  when: in_cluster

- include_tasks: "verify_zookeeper_{{ apb_action }}.yml"

- name: "Update last operation"
  asb_last_operation:
    description: "50%: Cluster objects state={{ state }}"
  when: in_cluster

- include_tasks: kafka.yml

- name: "Update last operation"
  asb_last_operation:
    description: "75%: Cluster objects state={{ state }}"
  when: in_cluster

- include_tasks: "verify_{{ apb_action }}.yml"


- name: "set fact service_uri state={{ state }}"
  include_tasks: "set_fact_service_uri.yml"
  when: state == "present"


- name: "set fact external_service_uri state={{ state }}"
  include_tasks: "set_fact_external_service_uri.yml"
  when:
    - state == "present"
    - external_enabled

- name: encode bind credentials
  asb_encode_binding:
    fields:
      user: admin
      password: "{{ admin_password }}"
      uri: "{{ hosts }}"
      tls_cacert: "{{ tls_cacert_lookup | b64encode }}"
  when:
    - state == "present"
    - tls_enabled
    - not external_enabled

- name: encode bind credentials
  asb_encode_binding:
    fields:
      user: admin
      password: "{{ admin_password }}"
      uri: "{{ hosts }}"
      external_uri: "{{ external_service_uri }}"
      tls_cacert: "{{ tls_cacert_lookup | b64encode }}"
  when:
    - state == "present"
    - tls_enabled
    - external_enabled

- name: encode bind credentials
  asb_encode_binding:
    fields:
      uri: "{{ hosts }}"
  when:
    - state == "present"
    - not tls_enabled

- name: "Update last operation"
  asb_last_operation:
    description: "100%: Done"
  when: in_cluster
