- name: nuxeo-mongodb-apb deprovision
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansibleplaybookbundle.asb-modules
  - role: nuxeo-mongodb-apb-provisioning
  vars:
    apb_action: deprovision
