---

- name: "Update last operation"
  asb_last_operation:
    description: "0%: Starting"
  when: in_cluster


- name: "Set ARender objects state={{ state }}"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.apply | default(True)
  loop:
    - name: arender_rendition_dc.yml.j2
    - name: arender_rendition_service.yml.j2

- name: "Wait for Rendition Deployment to become ready"
  debug:
    msg: "DeploymentConfig ready status: {{ arender_rendition_dc_query }}"
  retries: 20
  delay: 10
  until:
    - arender_rendition_dc_query
  when: state == 'present'


- name: "Update last operation"
  asb_last_operation:
    description: "100%: Cluster objects state={{ state }}"
  when: in_cluster
